### ISSUE TITLE
relabel_configs unmarshal errors

### ISSUE THREAD

**Issue by yackushevas** [voxpupuli/puppet-prometheus#160]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.4
- Ruby: 2.4.3p205p
- Distribution: Debian 8
- Module version: 4.0

## How to reproduce (e.g Puppet code you use)
part of the code from the hiera (json):
```
          "relabel_configs": [
            {
              "source_labels": "['__meta_consul_service']",
              "regex": "'(.*)'",
              "target_label": "service",
              "replacement": "$1"
            }
          ]
```

## What are you seeing

after converting to yaml:
```
  - "source_labels": >-
      ['__meta_consul_service']
     "regex": >-
       '(.*)'
    "target_label": >-
      'service'
     "replacement": >-
       '$1'
```

## What behaviour did you expect instead

    relabel_configs:
    - source_labels: ['__meta_consul_service']
      regex:         '(.*)'
      target_label:  'service'
      replacement:   '$1'

## Output log

> Error: /Stage[main]/Prometheus::Config/File[prometheus.yaml]/content: change from '{md5}8822bf5e2346fa4e41e3cfb3f5e1d3d2' to '{md5}465e86f9620ff98445bc84004f7d491b' failed: Execution of '/usr/local/bin/promtool check-config /etc/prometheus/prometheus.yaml20180215-2965-nsyebg' returned 1: Checking /etc/prometheus/prometheus.yaml20180215-2965-nsyebg
>   FAILED: yaml: unmarshal errors:
>   line 26: cannot unmarshal !!str `['__met...` into model.LabelNames

**Comment by yackushevas** [comment]
https://github.com/voxpupuli/puppet-prometheus/pull/104
if i use this code:

> <%= full_config.to_yaml.gsub(/source_labels: ".+?"/) { |x| x.gsub('"', '') } -%>

the problem goes away

**Comment by allangood** [comment]
I suggest to add the "module" parameter as well.
If you try to reproduce the sample config from blackbox_exporter:
```
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```
This puppet module will fail on both parameters: source_labels and module.

I tried this, and seems to be working just fine:
```
full_config.to_yaml.gsub(/(source_labels|module): ".+?"/) { |x| x.gsub('"', '') }
```
