### ISSUE TITLE
found multiple scrape configs with job name `x`

### ISSUE THREAD

**Issue by gsperry2011** [voxpupuli/puppet-prometheus#573]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.23.0
- Ruby: 
```
/opt/puppetlabs/puppet/bin/ruby --version
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]
```
- Distribution:  Red Hat Enterprise Linux Server release 7.9 (Maipo)
- Module version: puppet-prometheus (v12.0.0)

## How to reproduce (e.g Puppet code you use)

With heira that looks like this:
```
prometheus::scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: '15s'
    scrape_timeout: '10s'
    static_configs:
      - targets:
          - 'localhost:9090'
        labels:
          alias: 'Prometheus'
  - job_name: 'node'
    file_sd_configs:
      - files:
        - '/etc/prometheus/file_sd_config.d/targets.json'
    scrape_interval: '10s'
    scrape_timeout: '10s'
  - job_name: 'citrix-netscaler'
    metrics_path: /netscaler
    file_sd_configs:
      - files:
        - '/etc/prometheus/file_sd_config.d/citrix-netscaler_targets.json'
    scrape_interval: '10s'
    scrape_timeout: '10s'
    params:
      ignore-cert: ["yes"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9280  # The exporter's real hostname:port.
  - job_name: 'vmware'
    file_sd_configs:
      - files:
        - '/etc/prometheus/file_sd_config.d/vcenter_targets.json'
    scrape_interval: '30s'
    scrape_timeout: '30s'
 ```

## What are you seeing

```
Error: Execution of '/usr/local/bin/promtool check config /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42' returned 1: Checking /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42
  FAILED: parsing YAML file /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42: found multiple scrape configs with job name "prometheus"
Error: /Stage[main]/Prometheus::Config/File[prometheus.yaml]/content: change from '{md5}527af3b44940759988099e5a4ba8fff9' to '{md5}f437a06a306d9cdb82105bd6e752f710' failed: Execution of '/usr/local/bin/promtool check config /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42' returned 1: Checking /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42
  FAILED: parsing YAML file /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42: found multiple scrape configs with job name "prometheus"
  ```

## What behaviour did you expect instead

Prometheus to not detect duplicates because there aren't any in hiera. We have not changed these scrape targets for a long time and it works fine on prior versions of the puppet/prometheus module. We have been on `latest` for a while and had no issues on v11.2.0

## Output log

```
Notice: /Stage[main]/Prometheus::Config/File[prometheus.yaml]/content: 
--- /etc/prometheus/prometheus.yaml     2021-04-28 10:22:23.951707710 -0400
+++ /tmp/puppet-file20210728-1590-1fptvf        2021-07-28 11:42:21.572102877 -0400
@@ -12,6 +12,14 @@
 - "/etc/prometheus/rules/vmware.rules"
 scrape_configs:
 - job_name: prometheus
+  scrape_interval: 10s
+  scrape_timeout: 10s
+  static_configs:
+  - targets:
+    - localhost:9090
+    labels:
+      alias: Prometheus
+- job_name: prometheus
   scrape_interval: 15s
   scrape_timeout: 10s
   static_configs:

Error: Execution of '/usr/local/bin/promtool check config /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42' returned 1: Checking /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42
  FAILED: parsing YAML file /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42: found multiple scrape configs with job name "prometheus"
Error: /Stage[main]/Prometheus::Config/File[prometheus.yaml]/content: change from '{md5}527af3b44940759988099e5a4ba8fff9' to '{md5}f437a06a306d9cdb82105bd6e752f710' failed: Execution of '/usr/local/bin/promtool check config /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42' returned 1: Checking /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42
  FAILED: parsing YAML file /etc/prometheus/prometheus.yaml20210728-1590-1sxxp42: found multiple scrape configs with job name "prometheus"
  ```

## Any additional information you'd like to impart

Pinning the prometheus module to `11.2.0` works using the heira code I posted above.
