### ISSUE TITLE
statsd_exporter too opinionated about mappings

### ISSUE THREAD

**Issue by chadh** [voxpupuli/puppet-prometheus#680]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: all

## Any additional information you'd like to impart

We use a `/etc/statsd-exporter-mapping.yaml` that looks like this:
```
defaults:
  observer_type: histogram
  timer_type: histogram
  buckets: [ 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 2.0 ]
  match_type: glob
  glob_disable_ordering: false
  ttl: 0 # metrics do not expire
mappings:
- match: "(.*).counters\\.(.*)\\.(.*)\\.(.*)\\.(.*)\\.(.*)"
  match_type: regex
  name: "counters_$2_$3_$4_$5"
  labels:
      hostname: "$1"
      class: "$2"
      method: "$3"
      function: "$4"
      type: "$5"
      count: "$6"
- match: "(.*)\\.(filecount.*)\\.(.*)"
  ...
```
The `prometheus::statsd_exporter` assumes only a `mappings` hash in the config.   Rather than only passing in the contents of th `mappings` hash, it should either allow the entire file contents, or even just allow the user to manage the file.
